### PR TITLE
specify robot program

### LINKED ISSUE #4: Can't find options.txt on Windows
This seems to be caused by needing to include the build type (like linuxathena or windowsx86-64) before the buildtype when searching for options.txt

image

### PR DESCRIPTION
**Pull request by r4stered**
Fixes #4

This makes sure we specify the robot program executable for auto complete in options.txt

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
This brings up a fundamental flaw in the script where the compilation task name is hardcoded. In my other projects that use this script, I would just re-hardcode the compile task name to fit the project. With an example 2023.4.3 project, the compileTask is named `compileFrcUserProgramDebugExecutableFrcUserProgramCpp` and in my 2024.1.1-beta-3 project it's the same thing. Did you make any changes to the vanilla build configuration in your project? Perhaps this is another difference between linux/mac and windows.

**Comment by theVerySharpFlat** [comment]
@r4stered Actually, I think I know the reason for this difference. You enabled desktop builds and as a result, the build task names are different. I'm going to work on a way for the user to specify the build task name.

**Comment by theVerySharpFlat** [comment]
I think [ad40773](https://github.com/theVerySharpFlat/gradleRIO_CompilationDatabase/pull/5/commits/ad4077370f3d8ba10c5304b33bc198ff9c1ad3ce) solves the underlying issue of the #4. @r4stered can you confirm?

**Comment by r4stered** [comment]
```
(venv) PS C:\Users\willi\dev\testdrivebase> python .\rioCDGen.py --desktop     
searching for compiler... using C:\Users\Public\wpilib\2023\roborio\bin\arm-frc2023-linux-gnueabi-g++.exe
searching for options.txt...under task name"compileFrcUserProgramLinuxathenaDebugExecutableFrcUserProgramCpp"...
using C:\Users\willi\dev\testdrivebase\build\tmp\compileFrcUserProgramLinuxathenaDebugExecutableFrcUserProgramCpp\options.txt
getting compiler options... success
generating compile_commands.json...
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\Autos.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\Robot.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\RobotContainer.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\Alert.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\CTREPIDController.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\DataUtils.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\SimSwerveDrivetrain.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\SwerveDrivebase.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\SwerveModule.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\str\SwerveTelemetry.cpp
  generating definition for C:\Users\willi\dev\testdrivebase\src\main\cpp\subsystems\DrivebaseSubsystem.cpp
  failed to find object file for cpp file "C:\Users\willi\dev\testdrivebase\src\test\cpp\main.cpp". Skipping...
dumping to C:\Users\willi\dev\testdrivebase\compile_commands.json
```

@theVerySharpFlat yep! I specified --desktop and it worked!

**Pull request merged**
